# Generated by Django 2.0.2 on 2021-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Razorpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('oder_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payement_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
