# Generated by Django 2.0.2 on 2021-01-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpay',
            old_name='oder_id',
            new_name='order_id',
        ),
    ]
