# Generated by Django 2.0.2 on 2021-01-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razor', '0003_razorpay_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpay',
            old_name='razorpay_payement_id',
            new_name='razorpay_payment_id',
        ),
    ]
