# Generated by Django 2.0.2 on 2021-01-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razor', '0004_auto_20210129_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='services',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=100),
        ),
    ]
